openapi: "3.1.0"
info:
  title: Go JSON Web Service
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /doc/{docId}/{docPath}:
    get:
      summary: Retrieve existing (sub-)document.
      
      responses:
        '200': 
          $ref: "#/components/responses/200"
        '401': 
          $ref: "#/components/responses/401"
        '403': 
          $ref: "#/components/responses/403"
        '404': 
          $ref: "#/components/responses/404"
    post:
      summary: Accept an update to an existing document. If successful will return information about the document, and appropriate error information if not. 
      requestBody:
        description: JSON document to be processed
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200': 
          $ref: "#/components/responses/200"
        '400': 
          $ref: "#/components/responses/400"
        '401': 
          $ref: "#/components/responses/401"
        '403': 
          $ref: "#/components/responses/403"
        '404': 
          $ref: "#/components/responses/404"
        '422': 
          $ref: "#/components/responses/422"
  /doc/create:
    post:
      summary: Accepts a JSON document and returns it in the response
      requestBody:
        description: JSON document to be processed
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200': 
          $ref: "#/components/responses/200"
        '400': 
          $ref: "#/components/responses/400"
        '401': 
          $ref: "#/components/responses/401"
        '403': 
          $ref: "#/components/responses/403"
        '422': 
          $ref: "#/components/responses/422"
  /health:
    get:
      summary: Returns the health status of the server
      responses:
        '200':
          description: OK

components:
  responses:
    '200':
      description: JSON document was accepted, metadata about the new version is returned
      content:
        application/json:
          schema:
            type: object
    '400':
      description: JSON document was rejected due to it being not of the correct structure of the document. The returned JSON will contain additional information.
      content:
        application/json:
          schema:
            type: object
    '401':
      description: You are not authenticated correctly to access this resource. Authentication is required for each access to this API resource
      content:
        application/json:
          schema:
            type: object
    '403':
      description: You (or the user you are authenticated as) are not permitted to write to this resource.
      content:
        application/json:
          schema:
            type: object
    '404':
      description: The given resource does not exist. Please use the path '/doc/create' to create a new resource.
      content:
        application/json:
          schema:
            type: object
    '422':
      description: JSON document was rejected due some semantic error, but having correct structure and syntax. See the returned JSON for additional information.
      content:
        application/json:
          schema:
            type: object


