name: Generate Go Code from OpenAPI Spec
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Go code
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.yaml \
            -g go \
            -o /local/go-generated-code \
            --skip-validate-spec \
            --enable-post-process-file
      - name: Commit and push generated code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update generated Go code"
          branch: main
          commit_options: "--no-verify"
          file_pattern: "go-generated-code/**"
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
